In [1]:
import pandas as pd

In [8]:
A = pd.Series([2,3,4,5],index = ['a','b','c','d'])

In [9]:
A.values

array([2, 3, 4, 5], dtype=int64)

In [10]:
type(A.values)

numpy.ndarray

In [11]:
type(A)

pandas.core.series.Series

In [12]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
A['a']

2

In [14]:
A['d']

5

In [16]:
A[0]

2

In [18]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [7]:
grades_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grades = pd.Series(grades_dict)

In [8]:
grades

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [9]:
grades.values

array([4. , 3.5, 3. , 2.5])

In [10]:
marks_dict  = {'A':85,'B':91,'C':74,'D':55}
marks = pd.Series(marks_dict)

In [11]:
marks

A    85
B    91
C    74
D    55
dtype: int64

In [12]:
grades['A']

4.0

In [13]:
marks['D']

55

In [14]:
marks[0:3]

A    85
B    91
C    74
dtype: int64

In [15]:
marks_dict  = {'A':85,'B':91,'C':74,'D':55}
marks = pd.Series(marks_dict)

In [16]:
marks

A    85
B    91
C    74
D    55
dtype: int64

In [17]:
grades

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [18]:
import pandas as pd
D = pd.DataFrame({'Marks':marks,'Grades':grades})

In [19]:
D

Marks  Grades
A     85     4.0
B     91     3.5
C     74     3.0
D     55     2.5

In [20]:
D.T

A     B     C     D
Marks   85.0  91.0  74.0  55.0
Grades   4.0   3.5   3.0   2.5

In [21]:
D.values

array([[85. ,  4. ],
       [91. ,  3.5],
       [74. ,  3. ],
       [55. ,  2.5]])

In [22]:
D.values[3,0]

55.0

In [23]:
D['ScalesMarks'] = 100*(D['Marks'])/90

In [24]:
D

Marks  Grades  ScalesMarks
A     85     4.0    94.444444
B     91     3.5   101.111111
C     74     3.0    82.222222
D     55     2.5    61.111111

In [26]:
del D['ScalesMarks']

In [27]:
D

Marks  Grades
A     85     4.0
B     91     3.5
C     74     3.0
D     55     2.5

In [30]:
W = D[D['Marks']>70]

In [31]:
W

Marks  Grades
A     85     4.0
B     91     3.5
C     74     3.0

In [36]:
A = pd.DataFrame([{'a':1,'b':4},{'b':-3,'c':9}])

In [37]:
A

a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [40]:
A.fillna(0)

a  b    c
0  1.0  4  0.0
1  0.0 -3  9.0

In [41]:
A = pd.Series(['a','b','c'],[1,3,5])

In [42]:
A[1]

'a'

In [44]:
A[0:4]

1    a
3    b
5    c
dtype: object

In [47]:
A.loc[1:3]

1    a
3    b
dtype: object

In [49]:
A.iloc[1:3]

3    b
5    c
dtype: object

In [50]:
D

Marks  Grades
A     85     4.0
B     91     3.5
C     74     3.0
D     55     2.5

In [52]:
D.iloc[2,:]

Marks     74.0
Grades     3.0
Name: C, dtype: float64

In [61]:
D.iloc[3:]

Marks  Grades
D     55     2.5